# Generated by Django 4.2 on 2023-05-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summarize', '0002_remove_summary_summary_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='summary_url',
            new_name='link',
        ),
    ]
